### PR TITLE
Fix and update build actions

### LINKED ISSUE #41: Build failing on Ubuntu (Python 3.8+)
The last two build attempts have failed for `ubuntu-latest 3.8` and `3.9` (all other tests are passing). Specifically, we're getting an assertion error for three of the tests in `tests/test_examplecases.py::TestRCM`. Here's the failure message:
```
=========================== short test summary info ============================
FAILED tests/test_examplecases.py::TestRCM::test_few_steps_RCM - assert [0, 700759344...472986.069204] == [0, 700759344...473384.876724]
  At index 1 diff: 7007593448.337233 != 7007593448.337235
  Full diff:
  - [0, 7007593448.337235, 10439964733.462337, 13698473384.876724]
  ?                     ^           ^^^^ ^^^^         ^^ ^ ^^ ^
  + [0, 7007593448.337233, 10439964528.877066, 13698472986.069204]
  ?                     ^          +++++ ^^ ^         ^^ ^ ^ ^ +
FAILED tests/test_examplecases.py::TestRCM::test_set_time_RCM_previousdata - assert [0, 7007593448.337233] == [0, 7007593448.337235]
  At index 1 diff: 7007593448.337233 != 7007593448.337235
  Full diff:
  - [0, 7007593448.337235]
  ?                     ^
  + [0, 7007593448.337233]
  ?                     ^
FAILED tests/test_examplecases.py::TestRCM::test_set_time_RCM - assert [0, 7007593448.337233] == [0, 7007593448.337235]
  At index 1 diff: 7007593448.337233 != 7007593448.337235
  Full diff:
  - [0, 7007593448.337235]
  ?                     ^
  + [0, 7007593448.337233]
  ?                     ^
========================= 3 failed, 88 passed in 4.55s =========================
```

It looks to me like our random seed isn't guaranteeing identical travel times in newer versions of Python, because the error is occurring quite far down the list of sig-figs. The difference is on the order of 10^-8. I'm thinking an acceptable fix would be to change the assertion to check whether the results are within some threshold difference of each other, maybe 10^-6? Let me know if that works for you @elbeejay , happy to work on this later.

### PR DESCRIPTION
**Pull request by wrightky**
Should fix the assertion error for the three tests that were giving us trouble. Passed locally on Windows, still need to see if it passes the Ubuntu tests during auto-build. Closes #41

### CODE REVIEW

**Comment by wrightky** [comment]
Looks like (as of literally yesterday!) legacy Python 2.7 versions are no longer supported in GitHub actions. Will drop v2.7 from the build. 

In other news, the Ubuntu checks passed.

**Comment by elbeejay** [comment]
This looks good to me :+1:

**Comment by wrightky** [comment]
This PR is now a couple related updates to the build action:
- Tests have been fixed by using `pytest.approx` in for the tests that started returning an `AssertionError`
- Drops legacy Python 2.7 testing from `build.yml`, which is no longer supported by GitHub actions
- Adds Python 3.10 and 3.11 (both of which are passing, which is nice)
- Since Python 3.7 is nearing end of life in a couple weeks, updates the examples to be tested on 3.9 as the default

Let me know if this is worth incrementing the version number. Might be worth adding a new release to PyPI if only to update the version badge on the home page.

**Comment by elbeejay** [comment]
> This PR is now a couple related updates to the build action:
> 
> * Tests have been fixed by using `pytest.approx` in for the tests that started returning an `AssertionError`
> * Drops legacy Python 2.7 testing from `build.yml`, which is no longer supported by GitHub actions
> * Adds Python 3.10 and 3.11 (both of which are passing, which is nice)
> * Since Python 3.7 is nearing end of life in a couple weeks, updates the examples to be tested on 3.9 as the default
> 
> Let me know if this is worth incrementing the version number. Might be worth adding a new release to PyPI if only to update the version badge on the home page.

Dropping 2.7 from support is a milestone, I'd support a minor incrementation of the version number - it isn't really a breaking change so I don't think we need to move a full version up.

**Pull request merged**
